--- #YAML:1.0
name:                Rose-HTMLx-Form-Related
version:             0.11
abstract:            RHTMLO forms, living together
license:             ~
author:              
    - Peter Karman <karman@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Data::Dump:                    0
    Rose::HTML::Objects:           0
    Rose::HTMLx::Form::Field::Autocomplete: 0
    Rose::HTMLx::Form::Field::Boolean: 0
    Rose::HTMLx::Form::Field::Serial: 0.002
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
